<?php
namespace Kma\Component\Eqa\Site\Controller;
defined('_JEXEC') or die();

use Joomla\CMS\MVC\Controller\BaseController;

/* The DEFAULT controller for the front end */
class DisplayController extends BaseController
{
    public function display($cachable = false, $urlparams = [])
    {
        return parent::display($cachable, $urlparams); // TODO: Change the autogenerated stub
    }
}

